apiVersion: v1
kind: Service
metadata:
  name: bad-hash-service
spec:
  type: NodePort
  selector:
    app: bad-hash
  ports:
  - protocol: TCP
    port: 9010
    targetPort: 9010
    nodePort: 30010
