apiVersion: v1
kind: Service
metadata:
  name: bad-path-nginx-service
spec:
  selector:
    app: bad-path-nginx
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  selector:
    app: bad-path-app
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
