apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-path
  labels:
    app: bad-path
spec:
  selector:
    matchLabels:
      app: bad-path
  template:
    metadata:
      labels:
        app: bad-path
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: socat
          image: docker.pkg.github.com/kosenxmasctf/bad_path/bad_path:0.1.1
