apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-path-nginx
  labels:
    app: bad-path-nginx
spec:
  selector:
    matchLabels:
      app: bad-path-nginx
  template:
    metadata:
      labels:
        app: bad-path-nginx
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: socat
          image: docker.pkg.github.com/kosenxmasctf/bad_path/bad_path_nginx:0.1.3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-path-app
  labels:
    app: bad-path-app
spec:
  selector:
    matchLabels:
      app: bad-path-app
  template:
    metadata:
      labels:
        app: bad-path-app
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: socat
          image: docker.pkg.github.com/kosenxmasctf/bad_path/bad_path_app:0.1.3
