apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-hash
  labels:
    app: bad-hash
spec:
  selector:
    matchLabels:
      app: bad-hash
  template:
    metadata:
      labels:
        app: bad-hash
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: socat
          image: docker.pkg.github.com/kosenxmasctf/bad_hashj/bad_hash:0.1.0
