apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad_hash
  labels:
    app: bad_hash
spec:
  selector:
    matchLabels:
      app: bad_hash
  template:
    metadata:
      labels:
        app: bad_hash
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: socat
          image: docker.pkg.github.com/kosenxmasctf/bad_hashj/bad_hash:0.1.0
