apiVersion: apps/v1
kind: Deployment
metadata:
  name: beginners-shell
  labels:
    app: beginners-shell
spec:
  selector:
    matchLabels:
      app: beginners-shell
  template:
    metadata:
      labels:
        app: beginners-shell
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: socat
          image: docker.pkg.github.com/kosenxmasctf/beginners_shell/beginners_shell:0.1.0
