apiVersion: v1
kind: Service
metadata:
  name: dead-or-alive-service
spec:
  type: NodePort
  selector:
    app: dead-or-alive
  ports:
  - protocol: TCP
    port: 9005
    targetPort: 9005
    nodePort: 30005
