apiVersion: v1
kind: Service
metadata:
  name: decryptor-service
spec:
  type: NodePort
  selector:
    app: decryptor
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
    nodePort: 30013
