apiVersion: apps/v1
kind: Deployment
metadata:
  name: easy-heap
  labels:
    app: easy-heap
spec:
  selector:
    matchLabels:
      app: easy-heap
  template:
    metadata:
      labels:
        app: easy-heap
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: socat
          image: docker.pkg.github.com/kosenxmasctf/easy_heap/easy_heap:0.1.0
