apiVersion: v1
kind: Service
metadata:
  name: easy-heap-service
spec:
  type: NodePort
  selector:
    app: easy-heap
  ports:
  - protocol: TCP
    port: 9001
    targetPort: 9001
    nodePort: 30001
