apiVersion: v1
kind: Service
metadata:
  name: illigal-jump-service
spec:
  type: NodePort
  selector:
    app: illigal-jump
  ports:
  - protocol: TCP
    port: 9006
    targetPort: 9006
    nodePort: 30006
