apiVersion: apps/v1
kind: Deployment
metadata:
  name: illigal-jump
  labels:
    app: illigal-jump
spec:
  selector:
    matchLabels:
      app: illigal-jump
  template:
    metadata:
      labels:
        app: illigal-jump
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: socat
          image: docker.pkg.github.com/kosenxmasctf/illigal_jump/illigal_jump:0.1.0
