apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: name-virtual-host-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  tls:
  - hosts:
      - your-name.xm4s.net
      - hidden.your-name.xm4s.net
  rules:
  - host: your-name.xm4s.net
    http:
      paths:
      - backend:
          serviceName: your-name-service
          servicePort: 443
  - host: hidden.your-name.xm4s.net
    http:
      paths:
      - backend:
          serviceName: your-name-service
          servicePort: 443
  - host: sailor-or-blazor.xm4s.net
    http:
      paths:
      - backend:
          serviceName: sailor-or-blazor-service
          servicePort: 443
