apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: name-virtual-host-ingress
spec:
  rules:
  - host: your-name.xm4s.net
    http:
      paths:
      - backend:
          serviceName: your-name-service
          servicePort: 443
  - host: hidden.your-name.xm4s.net
    http:
      paths:
      - backend:
          serviceName: your-name-service
          servicePort: 443
