apiVersion: v1
kind: Service
metadata:
  name: match-flag-service
spec:
  type: NodePort
  selector:
    app: match-flag
  ports:
  - protocol: TCP
    port: 9003
    targetPort: 9003
    nodePort: 30009
