apiVersion: apps/v1
kind: Deployment
metadata:
  name: match-flag
  labels:
    app: match-flag
spec:
  selector:
    matchLabels:
      app: match-flag
  template:
    metadata:
      labels:
        app: match-flag
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: socat
          image: docker.pkg.github.com/kosenxmasctf/match_flag/match_flag:0.1.1
