apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinzoro
  labels:
    app: pinzoro
spec:
  selector:
    matchLabels:
      app: pinzoro
  template:
    metadata:
      labels:
        app: pinzoro
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: socat
          image: docker.pkg.github.com/kosenxmasctf/pinzoro/pinzoro:0.1.0
