apiVersion: apps/v1
kind: Deployment
metadata:
  name: sailor-or-blazor-app
  labels:
    app: sailor-or-blazor-app
spec:
  selector:
    matchLabels:
      app: sailor-or-blazor-app
  template:
    metadata:
      labels:
        app: sailor-or-blazor-app
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: socat
          image: docker.pkg.github.com/kosenxmasctf/bad_path/bad_path_app:0.1.2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sailor-or-blazor-nginx
  labels:
    app: sailor-or-blazor-nginx
spec:
  selector:
    matchLabels:
      app: sailor-or-blazor-nginx
  template:
    metadata:
      labels:
        app: sailor-or-blazor-nginx
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: socat
          image: docker.pkg.github.com/kosenxmasctf/bad_path/bad_path_nginx:0.1.2
