apiVersion: v1
kind: Service
metadata:
  name: super-type-service
spec:
  type: NodePort
  selector:
    app: super-type
  ports:
  - protocol: TCP
    port: 9008
    targetPort: 9008
    nodePort: 30008
