apiVersion: apps/v1
kind: Deployment
metadata:
  name: super-type
  labels:
    app: super-type
spec:
  selector:
    matchLabels:
      app: super-type
  template:
    metadata:
      labels:
        app: super-type
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: socat
          image: docker.pkg.github.com/kosenxmasctf/super_type/super_type:0.1.0
