apiVersion: v1
kind: Service
metadata:
  name: what-is-include-service
spec:
  type: NodePort
  selector:
    app: what-is-include
  ports:
  - protocol: TCP
    port: 9004
    targetPort: 9004
    nodePort: 30004
