apiVersion: apps/v1
kind: Deployment
metadata:
  name: write-where-what
  labels:
    app: write-where-what
spec:
  selector:
    matchLabels:
      app: write-where-what
  template:
    metadata:
      labels:
        app: write-where-what
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: socat
          image: docker.pkg.github.com/kosenxmasctf/write_where_what/write_where_what:0.1.0
