apiVersion: v1
kind: Service
metadata:
  name: write-where-what-service
spec:
  type: NodePort
  selector:
    app: write-where-what
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
    nodePort: 30003
