apiVersion: v1
kind: Service
metadata:
  name: write-where-what-service
spec:
  type: NodePort
  selector:
    app: write-where-what
  ports:
  - protocol: TCP
    port: 9003
    targetPort: 9003
    nodePort: 30003
