apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-name-hidden
  labels:
    app: your-name-hidden
spec:
  selector:
    matchLabels:
      app: your-name-hidden
  template:
    metadata:
      labels:
        app: your-name-hidden
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: hidden
          image: docker.pkg.github.com/kosenxmasctf/your_name/your_name_hidden:0.1.1
