apiVersion: apps/v1
kind: Deployment
metadata:
  name: your_name
  labels:
    app: your_name
spec:
  selector:
    matchLabels:
      app: your_name
  template:
    metadata:
      labels:
        app: your_name
    spec:
      containers:
      - name: your-name-main
        image: docker.pkg.github.com/kosenxmasctf/your_name/your_name:latest
